ktor:
  deployment:
    port: 8080
  application:
    modules:
      - moe.tabidachi.HttpKt.configureHttp
      - moe.tabidachi.SerializationKt.configureSerialization
      - moe.tabidachi.SecurityKt.configureSecurity
      - moe.tabidachi.SseKt.configureSse
      - moe.tabidachi.StatusPagesKt.configureStatusPages
      - moe.tabidachi.DIKt.configureDependencyInjection
      - moe.tabidachi.KoinKt.configureKoin
      - moe.tabidachi.ExposedKt.configureExposed
      - moe.tabidachi.PostgresKt.configurePostgres
      - moe.tabidachi.WebsocketsKt.configureWebsockets
      - moe.tabidachi.RoutingKt.configureRouting
